#!/usr/bin/env python3
"""Generate src/generated/tones_data.c + include/generated/tones.h.

Adapted from reverse_3210 scripts/generate_pico_c_tones.py with the Sisu
identifier scheme (ringtone_t, unprefixed function names, generated/tones.h).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "vendor"))
from extract_ppm_chunks import firmware_note_frequency_table  # noqa: E402


def c_ident(text: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]+", "_", text).strip("_").lower()


def c_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def emit_bytes(out: list[str], name: str, data: bytes) -> None:
    out.append(f"static const uint8_t {name}[] = {{")
    if data:
        for offset in range(0, len(data), 16):
            chunk = data[offset : offset + 16]
            out.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    out.append("};")
    out.append("")


# Ringtone manifest index -> (v6.00 Ringing-tone setting value, display label),
# traced from the original settings menu (reverse_3210 tone_settings trace).
RINGTONE_MAP = (
    (0, 20, "Ring ring"),
    (1, 21, "Low"),
    (2, 26, "Intro"),
    (3, 23, "Mosquito"),
    (4, 73, "Samba"),
    (5, 25, "Bee"),
    (6, 52, "Nokia tune"),
    (7, 31, "City bird"),
    (8, 63, "Attraction"),
    (9, 69, "Cladoceran"),
    (10, 64, "Dawn"),
    (11, 38, "Kick"),
    (12, 108, "Bumblebee"),
    (13, 47, "That's it!"),
    (14, 34, "Chase"),
    (15, 98, "Mexican Hat Dance"),
    (16, 99, "Entertainer"),
    (17, 43, "Playground"),
    (18, 54, "Fuga"),
    (19, 50, "Rocket"),
    (20, 42, "Happy return"),
    (21, 103, "Valkyrie"),
    (22, 102, "Auld Lang Syne"),
    (23, 62, "Polska"),
    (24, 48, "Progress"),
    (25, 78, "Jumping"),
    (26, 55, "Menuet"),
    (27, 60, "William Tell"),
    (28, 76, "Charleston"),
    (29, 93, "Matilda"),
    (30, 91, "Brave Scotland"),
    (31, 97, "Reveille"),
    (32, 90, "Jingle bells"),
    (33, 85, "Four seasons"),
    (34, 104, "Bossanova"),
    (35, 106, "HipHop"),
    (36, 107, "Salsa"),
    (37, 109, "Hurdy-gurdy"),
)


def ringtone_maps() -> tuple[dict[int, int], dict[int, str]]:
    values = {index: value for index, value, _ in RINGTONE_MAP}
    labels = {index: label for index, _, label in RINGTONE_MAP}
    return values, labels


HEADER_TEXT = """/* Auto-generated by scripts/generate_pico_c_tones.py. */
/* Source: Nokia 3210 v6.00 original tone bytecode resources. */

#ifndef GENERATED_TONES_H
#define GENERATED_TONES_H

#include <stdint.h>

typedef struct {
    uint8_t index;
    uint8_t value;
    const char *name;
    const uint8_t *data;
    uint16_t length;
} ringtone_t;

uint8_t ringtone_count(void);
const ringtone_t *ringtone_at(uint8_t index);
const ringtone_t *ringtone_by_index(uint8_t index);
const ringtone_t *ringtone_by_value(uint8_t value);
const uint8_t *system_tone_data(uint8_t index, uint16_t *out_len);
uint16_t tone_frequency_hz(uint8_t pitch);

#endif
"""


def generate_source(fls_path: Path, ringtone_dir: Path, system_dir: Path,
                    out_c: Path) -> None:
    value_by_index, label_by_index = ringtone_maps()
    ringtone_paths = sorted(ringtone_dir.glob("*.tone.bin"))
    system_paths = sorted(system_dir.glob("*_system.bin"))
    full_flash = fls_path.read_bytes()
    freq_table = firmware_note_frequency_table(full_flash)

    out: list[str] = [
        "/* Auto-generated by scripts/generate_pico_c_tones.py. */",
        "/* Source: Nokia 3210 v6.00 original tone bytecode resources. */",
        "",
        '#include "generated/tones.h"',
        "",
        "#include <stddef.h>",
        "",
    ]

    ringtone_rows: list[tuple[int, int, str, str, int]] = []
    for path in ringtone_paths:
        index = int(path.name[:2])
        data = path.read_bytes()
        name = f"g_ringtone_{index:02d}_{c_ident(label_by_index.get(index, path.stem))}"
        emit_bytes(out, name, data)
        ringtone_rows.append((index, value_by_index[index], label_by_index[index], name, len(data)))

    system_rows: list[tuple[int, str, int]] = []
    for path in system_paths:
        index = int(path.name[:2])
        data = path.read_bytes()
        name = f"g_system_tone_{index:02d}"
        emit_bytes(out, name, data)
        system_rows.append((index, name, len(data)))

    out.append("static const ringtone_t G_RINGTONES[] = {")
    for index, value, label, data_name, length in ringtone_rows:
        out.append(
            f'    {{{index}u, {value}u, "{c_string(label)}", {data_name}, {length}u}},'
        )
    out.append("};")
    out.append("")

    max_system_index = max((row[0] for row in system_rows), default=0)
    system_lookup = {row[0]: row for row in system_rows}
    out.append(f"static const uint8_t *const G_SYSTEM_TONES[{max_system_index + 1}u] = {{")
    for index in range(max_system_index + 1):
        row = system_lookup.get(index)
        out.append(f"    [{index}u] = {row[1] if row else '0'},")
    out.append("};")
    out.append("")
    out.append(f"static const uint16_t G_SYSTEM_TONE_LENGTHS[{max_system_index + 1}u] = {{")
    for index in range(max_system_index + 1):
        row = system_lookup.get(index)
        out.append(f"    [{index}u] = {row[2] if row else 0}u,")
    out.append("};")
    out.append("")

    out.append("static const uint16_t G_NOTE_FREQ[0xa5u - 0x40u] = {")
    for pitch in range(0x40, 0xA5):
        out.append(f"    [{pitch - 0x40}u] = {freq_table.get(pitch, 0)}u,")
    out.append("};")
    out.append("")

    out.extend(
        [
            "uint8_t ringtone_count(void) {",
            "    return (uint8_t)(sizeof(G_RINGTONES) / sizeof(G_RINGTONES[0]));",
            "}",
            "",
            "const ringtone_t *ringtone_at(uint8_t index) {",
            "    return index < ringtone_count() ? &G_RINGTONES[index] : 0;",
            "}",
            "",
            "const ringtone_t *ringtone_by_index(uint8_t index) {",
            "    for (uint8_t i = 0; i < ringtone_count(); i++) {",
            "        if (G_RINGTONES[i].index == index) {",
            "            return &G_RINGTONES[i];",
            "        }",
            "    }",
            "    return 0;",
            "}",
            "",
            "const ringtone_t *ringtone_by_value(uint8_t value) {",
            "    for (uint8_t i = 0; i < ringtone_count(); i++) {",
            "        if (G_RINGTONES[i].value == value) {",
            "            return &G_RINGTONES[i];",
            "        }",
            "    }",
            "    return 0;",
            "}",
            "",
            "const uint8_t *system_tone_data(uint8_t index, uint16_t *out_len) {",
            "    if (index >= (sizeof(G_SYSTEM_TONES) / sizeof(G_SYSTEM_TONES[0])) ||",
            "        G_SYSTEM_TONES[index] == 0) {",
            "        if (out_len != 0) {",
            "            *out_len = 0;",
            "        }",
            "        return 0;",
            "    }",
            "    if (out_len != 0) {",
            "        *out_len = G_SYSTEM_TONE_LENGTHS[index];",
            "    }",
            "    return G_SYSTEM_TONES[index];",
            "}",
            "",
            "uint16_t tone_frequency_hz(uint8_t pitch) {",
            "    if (pitch < 0x40u || pitch > 0xa4u) {",
            "        return 0;",
            "    }",
            "    return G_NOTE_FREQ[pitch - 0x40u];",
            "}",
            "",
        ]
    )

    out_c.parent.mkdir(parents=True, exist_ok=True)
    out_c.write_text("\n".join(out), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fls", type=Path, required=True)
    parser.add_argument("--ringtones", type=Path, required=True)
    parser.add_argument("--system-tones", type=Path, required=True)
    parser.add_argument("--out-c", type=Path, required=True)
    parser.add_argument("--out-h", type=Path, required=True)
    args = parser.parse_args()
    args.out_h.parent.mkdir(parents=True, exist_ok=True)
    args.out_h.write_text(HEADER_TEXT, encoding="utf-8")
    generate_source(args.fls, args.ringtones, args.system_tones, args.out_c)
    print(f"wrote {args.out_c}")
    print(f"wrote {args.out_h}")


if __name__ == "__main__":
    main()
