#!/usr/bin/env python3
"""Generate src/generated/assets_data.c from the traced font/bitmap JSONs.

Adapted from reverse_3210 scripts/generate_pico_c_assets.py with the Sisu
identifier scheme (ui/assets.h types: glyph_t/font_t/bitmap_t/bitmap_store_t,
g_fonts/g_bitmaps, FONT_*).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

FONT_SOURCES = (
    ("FS0", "FONT_FS0", "3210600c_full_largebold.json"),
    ("FS1", "FONT_FS1", "3210600c_full_smallplain.json"),
    ("FS2", "FONT_FS2", "3210600c_full_smallbold.json"),
    ("FS3", "FONT_FS3", "3210600c_full_tinyplain.json"),
    ("FS4", "FONT_FS4", "3210600c_full_ftestplain.json"),
)


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def font_records(path: Path) -> list[tuple[int, int, int, bytes]]:
    data = load_json(path)
    records = []
    for glyph in data.get("glyphs", []):
        cp = int(glyph["codepoint"])
        if cp < 0x20:
            continue
        records.append(
            (
                cp,
                int(glyph["width"]),
                int(glyph["height"]),
                bytes.fromhex(glyph.get("packed_vertical_lsb_hex") or ""),
            )
        )
    return sorted(records, key=lambda item: item[0])


def bitmap_records(path: Path) -> list[tuple[int, int, int, bytes]]:
    data = load_json(path)
    records = []
    for item in data.get("glyphs", []):
        records.append(
            (
                int(item.get("id") or item.get("codepoint")),
                int(item["width"]),
                int(item["height"]),
                bytes.fromhex(item.get("packed_vertical_lsb_hex") or ""),
            )
        )
    return sorted(records, key=lambda item: item[0])


# React playfield bitmaps read straight from the flash (CPU address, id,
# width, height). The packed VLSB bytes live verbatim at these addresses;
# CPU base is 0x00200000.
REACT_BITMAPS = (
    (0x002D9764, 300, 84, 48),
    (0x002D99FC, 301, 10, 10),
    (0x002D9A10, 302, 5, 5),
    (0x002D9A20, 303, 4, 2),
)
CPU_BASE = 0x00200000


def react_bitmap_records(fls_path: Path) -> list[tuple[int, int, int, bytes]]:
    fls = fls_path.read_bytes()
    records = []
    for address, bitmap_id, width, height in REACT_BITMAPS:
        banks = (height + 7) // 8
        offset = address - CPU_BASE
        packed = bytearray(fls[offset:offset + banks * width])
        if len(packed) != banks * width:
            raise SystemExit(f"react bitmap 0x{address:08x} out of range")
        # Mask padding bits in the final partial bank: the firmware's fast
        # VLSB blit paints whole bytes, so stray bits above `height` would
        # otherwise leak onto the screen.
        if height % 8:
            mask = (1 << (height % 8)) - 1
            for col in range(width):
                index = (banks - 1) * width + col
                packed[index] &= mask
        records.append((bitmap_id, width, height, bytes(packed)))
    return records


def c_ident(name: str) -> str:
    return name.lower().replace("-", "_")


def emit_bytes(out: list[str], name: str, data: bytes) -> None:
    out.append(f"static const uint8_t {name}[] = {{")
    if data:
        for index in range(0, len(data), 16):
            chunk = data[index : index + 16]
            out.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    out.append("};")
    out.append("")


def emit_glyphs(out: list[str], name: str, records: list[tuple[int, int, int, bytes]]) -> bytes:
    blob = bytearray()
    rows = []
    for cp, width, height, packed in records:
        offset = len(blob)
        blob.extend(packed)
        rows.append((cp, width, height, offset))
    out.append(f"static const glyph_t {name}[] = {{")
    for cp, width, height, offset in rows:
        out.append(f"    {{0x{cp:04x}, {width}u, {height}u, {offset}u}},")
    out.append("};")
    out.append("")
    return bytes(blob)


def emit_bitmaps(out: list[str], name: str, records: list[tuple[int, int, int, bytes]]) -> bytes:
    blob = bytearray()
    rows = []
    for bitmap_id, width, height, packed in records:
        offset = len(blob)
        blob.extend(packed)
        rows.append((bitmap_id, width, height, offset))
    out.append(f"static const bitmap_t {name}[] = {{")
    for bitmap_id, width, height, offset in rows:
        out.append(f"    {{{bitmap_id}u, {width}u, {height}u, {offset}u}},")
    out.append("};")
    out.append("")
    return bytes(blob)


def generate(fonts_dir: Path, bitmap_path: Path, react_fls: Path, output: Path) -> dict:
    out = [
        "/* Auto-generated by scripts/generate_pico_c_assets.py. */",
        "/* Source: Nokia 3210 v6.00 reversed firmware assets. */",
        "",
        '#include "ui/assets.h"',
        "",
    ]

    font_meta = []
    for font_name, enum_name, filename in FONT_SOURCES:
        records = font_records(fonts_dir / filename)
        ident = c_ident(font_name)
        glyph_name = f"g_{ident}_glyphs"
        data_name = f"g_{ident}_data"
        blob = emit_glyphs(out, glyph_name, records)
        emit_bytes(out, data_name, blob)
        height = max((row[2] for row in records), default=0)
        font_meta.append((font_name, enum_name, glyph_name, len(records), data_name, len(blob), height))

    bitmaps = bitmap_records(bitmap_path)
    bitmaps += react_bitmap_records(react_fls)
    bitmaps.sort(key=lambda item: item[0])
    bitmap_blob = emit_bitmaps(out, "g_bitmap_items", bitmaps)
    emit_bytes(out, "g_bitmap_data", bitmap_blob)

    out.append("const font_t g_fonts[FONT_COUNT] = {")
    for font_name, enum_name, glyph_name, glyph_count, data_name, data_size, height in font_meta:
        out.append(
            f"    [{enum_name}] = {{\"{font_name}\", {glyph_name}, {glyph_count}u, "
            f"{data_name}, {data_size}u, {height}u, 0u}},"
        )
    out.append("};")
    out.append("")
    out.append(
        "const bitmap_store_t g_bitmaps = "
        f"{{g_bitmap_items, {len(bitmaps)}u, g_bitmap_data, {len(bitmap_blob)}u}};"
    )
    out.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(out), encoding="ascii")
    return {
        "fonts": {name: count for name, _, _, count, _, _, _ in font_meta},
        "bitmaps": len(bitmaps),
        "bitmap_data_bytes": len(bitmap_blob),
        "output": str(output),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fonts-dir", type=Path, required=True)
    parser.add_argument("--bitmaps", type=Path, required=True)
    parser.add_argument("--fls", type=Path, required=True,
                        help="flash image; react playfield bitmaps are read from it")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(generate(args.fonts_dir, args.bitmaps, args.fls, args.output), indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
