#ifndef APP_INTERNAL_H
#define APP_INTERNAL_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "app.h"
#include "ui/assets.h"
#include "ui/framebuffer.h"
#include "ui/ui.h"

#define ARRAY_COUNT(a) (sizeof(a) / sizeof((a)[0]))

typedef enum {
    PHONEBOOK_LABEL_CALL = 0,
    PHONEBOOK_LABEL_EDIT,
    PHONEBOOK_LABEL_ERASE,
    PHONEBOOK_LABEL_ASSIGN,
    PHONEBOOK_LABEL_SEND,
    PHONEBOOK_LABEL_OK,
} phonebook_label_t;

typedef enum {
    PHONEBOOK_CONTEXT_NONE = 0,
    PHONEBOOK_CONTEXT_SEARCH,
    PHONEBOOK_CONTEXT_STANDBY,
    PHONEBOOK_CONTEXT_EDIT,
    PHONEBOOK_CONTEXT_ERASE,
    PHONEBOOK_CONTEXT_ASSIGN,
    PHONEBOOK_CONTEXT_SEND,
    PHONEBOOK_CONTEXT_SPEED_ASSIGN,
    PHONEBOOK_CONTEXT_SEND_RECIPIENT,
    PHONEBOOK_CONTEXT_SMS_RECIPIENT,
    PHONEBOOK_CONTEXT_PICTURE_RECIPIENT,
    PHONEBOOK_CONTEXT_TONE_COMPOSER_RECIPIENT,
    PHONEBOOK_CONTEXT_CALL_REGISTER_SAVE,
    PHONEBOOK_CONTEXT_IN_CALL,
    PHONEBOOK_CONTEXT_IN_CALL_NEW_CALL,
} phonebook_context_t;

typedef enum {
    EDITOR_KIND_TEXT = 0,
    EDITOR_KIND_NUMBER,
} editor_kind_t;

typedef enum {
    EDITOR_MODE_UPPER = 0,
    EDITOR_MODE_LOWER,
    EDITOR_MODE_NUMERIC,
} editor_mode_t;

typedef enum {
    EDITOR_CONTEXT_NONE = 0,
    EDITOR_CONTEXT_PHONEBOOK_SEARCH,
    EDITOR_CONTEXT_PHONEBOOK_ADD_NAME,
    EDITOR_CONTEXT_PHONEBOOK_ADD_NUMBER,
    EDITOR_CONTEXT_PHONEBOOK_EDIT_NAME,
    EDITOR_CONTEXT_PHONEBOOK_EDIT_NUMBER,
    EDITOR_CONTEXT_PHONEBOOK_SEND_RECIPIENT,
    EDITOR_CONTEXT_CALL_REGISTER_EDIT_NUMBER,
    EDITOR_CONTEXT_SMS_RECIPIENT,
    EDITOR_CONTEXT_PICTURE_RECIPIENT,
    EDITOR_CONTEXT_SMS_MESSAGE_CENTRE,
    EDITOR_CONTEXT_VOICE_MAILBOX_NUMBER,
    EDITOR_CONTEXT_SMS_T9_INSERT_WORD,
    EDITOR_CONTEXT_SMS_T9_INSERT_NUMBER,
    EDITOR_CONTEXT_SETTINGS_WELCOME_NOTE,
    EDITOR_CONTEXT_SETTINGS_PIN_REQUEST,
    EDITOR_CONTEXT_SETTINGS_ACCESS_CODE,
    EDITOR_CONTEXT_CALL_DIVERT_OTHER_NUMBER,
    EDITOR_CONTEXT_TONE_COMPOSER_NAME,
    EDITOR_CONTEXT_TONE_COMPOSER_RECIPIENT,
    EDITOR_CONTEXT_IN_CALL_NEW_CALL,
    EDITOR_CONTEXT_IN_CALL_DTMF,
} editor_context_t;

typedef enum {
    CONFIRM_CONTEXT_NONE = 0,
    CONFIRM_CONTEXT_PHONEBOOK_ERASE,
    CONFIRM_CONTEXT_PHONEBOOK_ERASE_ALL,
    CONFIRM_CONTEXT_CALL_REGISTER_ERASE,
    CONFIRM_CONTEXT_PICTURE_MESSAGE_ERASE,
    CONFIRM_CONTEXT_PICTURE_MESSAGE_SAVE_FIRST,
    CONFIRM_CONTEXT_TONES_RINGING_VOLUME,
} confirm_context_t;

void resolve_contact_name(const char *number, char *dst, size_t cap);

#endif
