#ifndef BATTERY_CHARGE_SUPERVISOR_SERVICE_H
#define BATTERY_CHARGE_SUPERVISOR_SERVICE_H

#include <stdbool.h>
#include <stdint.h>

#include "services/battery_charge_supervisor_logic.h"

#define BATTERY_CHARGE_SUPERVISOR_TRACE_CAP 16u

typedef enum {
    BATTERY_CHARGE_MAINTENANCE_IDLE = 0,
    BATTERY_CHARGE_MAINTENANCE_WAIT_INHIBIT,
    BATTERY_CHARGE_MAINTENANCE_RESET_HOLD,
    BATTERY_CHARGE_MAINTENANCE_WAIT_RELEASE,
} battery_charge_maintenance_phase_t;

typedef struct {
    battery_charge_supervisor_snapshot_t model;
    bool initialized;
    bool storage_unavailable;
    bool restore_pending;
    bool restored_after_reset;
    bool persistence_pending;
    uint32_t update_count;
    uint32_t attach_events;
    uint32_t admission_events;
    uint32_t terminal_events;
    uint32_t minute_events;
    uint32_t restore_attempts;
    uint32_t restore_successes;
    uint32_t restore_failures;
    uint32_t persistence_requests;
    uint32_t persistence_failures;
    uint32_t control_requests;
    uint32_t control_failures;
    uint32_t maintenance_rearm_events;
    uint32_t bq_recovery_events;
    uint32_t last_model_result;
    bool release_inhibit_pending;
    battery_charge_maintenance_phase_t maintenance_phase;
    bool maintenance_full_hold;
    bool maintenance_soc_ready;
    bool maintenance_voltage_ready;
    uint16_t maintenance_voltage_mv;
    uint32_t shadow_compares;
    uint32_t shadow_matches;
    uint32_t shadow_mismatches;
    bool shadow_last_active_match;
    bool shadow_last_completion_match;
    uint8_t trace_count;
    uint8_t trace_next;
    battery_charge_supervisor_persisted_t persisted;
} battery_charge_supervisor_service_snapshot_t;

typedef enum {
    BATTERY_CHARGE_CONFIG_OK = 0,
    BATTERY_CHARGE_CONFIG_INVALID_ARGUMENT,
    BATTERY_CHARGE_CONFIG_SESSION_ACTIVE,
    BATTERY_CHARGE_CONFIG_STORE_NOT_READY,
    BATTERY_CHARGE_CONFIG_STORE_ERROR,
} battery_charge_supervisor_config_status_t;

/* Called after store_service_init() but before the TCA charger-control output
 * is initialized. A durable stop latch must own /CE from its first driven
 * level after any RP reset. */
bool battery_charge_supervisor_service_boot_inhibit_required(void);

void battery_charge_supervisor_service_init(void);

/* Opportunistic sidecar poll. It creates no timer or wake deadline. In an
 * explicitly provisioned enforcement policy it may request the supervisor's
 * additive charger-inhibit owner, but only after its stop latch is durable. */
uint32_t battery_charge_supervisor_service_poll(uint32_t now_ms);

/* Release only this service's /CE owner when app-side LOW/EMPTY evidence says
 * an attached pack is not actually recovering. Hardware release is fail-open;
 * the cleared latch is still retried to durability before model re-admission. */
bool battery_charge_supervisor_service_release_for_battery_floor(void);

/* CDC-only provisioning seam. Refused while a charger/session/latch is live.
 * A successful return means the journal RAM owner accepted the configuration;
 * callers can inspect the store dirty bit for flash durability. */
battery_charge_supervisor_config_status_t
battery_charge_supervisor_service_configure(
    battery_charge_supervisor_policy_t policy,
    uint16_t charge_factor_permille,
    bool factor_confident);

/* One accounting calibration for both the supervisor target and the learner's
 * charge-side SOC projection. Returns the configured value when present and
 * otherwise the active hardware profile's prior. */
uint16_t
battery_charge_supervisor_service_effective_charge_factor_permille(void);

/* Compare one old production transition against the model result generated by
 * the immediately preceding poll. This is diagnostic only. */
void battery_charge_supervisor_service_note_legacy(bool active,
                                                   bool completed);

void battery_charge_supervisor_service_get_snapshot(
    battery_charge_supervisor_service_snapshot_t *out);

/* Index zero is the oldest retained minute. */
bool battery_charge_supervisor_service_get_trace(
    uint8_t index, battery_charge_supervisor_minute_t *out);

#endif
