#ifndef NETMON_CONTROL_TYPES_H
#define NETMON_CONTROL_TYPES_H

typedef enum {
    NETMON_ACTION_NONE = 0,
    NETMON_ACTION_OUTPUT_TEST,
    NETMON_ACTION_BATTERY_SIM,
    NETMON_ACTION_CHARGER,
    NETMON_ACTION_HEADSET_FORCE,
    NETMON_ACTION_CONVERTER_MODE,
    NETMON_ACTION_LCD_CALIBRATION,
    NETMON_ACTION_MEASUREMENT_RESET,
    NETMON_ACTION_NO_SERVICE_TIMER,
    NETMON_ACTION_BAND_TEST,
    NETMON_ACTION_ANTENNA_MAINTENANCE,
    NETMON_ACTION_BACKLIGHT_LEVEL,
} netmon_action_t;

typedef enum {
    NETMON_CONTROL_KEY_0 = 0,
    NETMON_CONTROL_KEY_1,
    NETMON_CONTROL_KEY_2,
    NETMON_CONTROL_KEY_3,
    NETMON_CONTROL_KEY_4,
    NETMON_CONTROL_KEY_5,
    NETMON_CONTROL_KEY_6,
    NETMON_CONTROL_KEY_7,
    NETMON_CONTROL_KEY_8,
    NETMON_CONTROL_KEY_9,
    NETMON_CONTROL_KEY_STAR,
    NETMON_CONTROL_KEY_HASH,
    NETMON_CONTROL_KEY_INVALID,
} netmon_control_key_t;

#endif
