# Generate generated/build_info.h with the short git commit hash + build date.
# Run at build time (from an always-run custom target) so the values track the
# actual build, not the last cmake configure. The header is only rewritten when
# its content changes, so a dependent source (service_codes_app.c) is recompiled
# only when the hash or date actually changes -- not on every build.
#
# Invoked as:
#   cmake -DOUT=<build_info.h path> -DSRC_DIR=<repo root> -P gen_build_info.cmake

if(NOT DEFINED OUT)
    message(FATAL_ERROR "gen_build_info.cmake requires -DOUT=<path>")
endif()
if(NOT DEFINED SRC_DIR)
    message(FATAL_ERROR "gen_build_info.cmake requires -DSRC_DIR=<repo root>")
endif()

# Short commit hash. Fall back gracefully if git is missing or this is not a repo
# (e.g. a source tarball) so the build never fails on the version string.
execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY "${SRC_DIR}"
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE GIT_RESULT
)
if(NOT GIT_RESULT EQUAL 0 OR GIT_HASH STREQUAL "")
    set(GIT_HASH "nogit")
endif()

# Mark the stamp "-dirty" when the compiled SOURCE has uncommitted changes, so a
# bench build can't be mistaken for the clean commit. Scoped to source paths that
# affect the binary -- docs stay uncommitted by project rule (the tree is always
# dirty w.r.t. them), so a whole-tree check would always trip and be useless.
if(NOT GIT_HASH STREQUAL "nogit")
    execute_process(
        COMMAND git status --porcelain -- src include CMakeLists.txt cmake boards
        WORKING_DIRECTORY "${SRC_DIR}"
        OUTPUT_VARIABLE GIT_DIRTY
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE GIT_DIRTY_RESULT
    )
    if(GIT_DIRTY_RESULT EQUAL 0 AND NOT GIT_DIRTY STREQUAL "")
        set(GIT_HASH "${GIT_HASH}-dirty")
    endif()
endif()

string(TIMESTAMP BUILD_DATE "%Y-%m-%d")

set(CONTENT
"/* Auto-generated by cmake/gen_build_info.cmake at build time. Do not edit. */
#ifndef SISU_BUILD_INFO_H
#define SISU_BUILD_INFO_H
#define SISU_BUILD_HASH \"${GIT_HASH}\"
#define SISU_BUILD_DATE \"${BUILD_DATE}\"
#endif
")

# Only rewrite when changed, to avoid needless recompiles.
set(EXISTING "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" EXISTING)
endif()
if(NOT EXISTING STREQUAL CONTENT)
    file(WRITE "${OUT}" "${CONTENT}")
endif()
